package d1

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"

	"github.com/planetscale/cli/internal/postgres"
)

var (
	sqliteTypeCleanup = regexp.MustCompile(`(?i)\s+PRIMARY\s+KEY\s+AUTOINCREMENT`)
)

// SchemaParts holds table DDL and secondary index DDL separately so imports can
// load data before building indexes (much faster than maintaining indexes per row).
type SchemaParts struct {
	Tables  string
	Indexes string
}

// ConvertSchemaParts converts SQLite DDL into Postgres table and index SQL.
func ConvertSchemaParts(inputPath string) (SchemaParts, int, error) {
	tables, err := ParseDump(inputPath)
	if err != nil {
		return SchemaParts{}, 0, err
	}

	coerceCtx, err := BuildTypeCoercionContext(inputPath, tables)
	if err != nil {
		return SchemaParts{}, 0, err
	}

	indexes, err := ParseIndexes(inputPath)
	if err != nil {
		return SchemaParts{}, 0, err
	}

	var tableBuf strings.Builder
	tableBuf.WriteString("-- Generated by pscale import d1 convert-schema (tables)\n")
	fmt.Fprintf(&tableBuf, "-- Source: %s\n\n", inputPath)

	converted := 0
	tableByName := make(map[string]TableSchema, len(tables))
	for _, table := range tables {
		tableByName[table.Name] = table
	}
	for _, name := range topologicalLoadOrder(tables) {
		table, ok := tableByName[name]
		if !ok {
			continue
		}
		if IsORMMetadataTable(table.Name) {
			continue
		}
		tableBuf.WriteString(convertTableDDL(table, tables, coerceCtx))
		tableBuf.WriteString("\n\n")
		converted++
	}

	var indexBuf strings.Builder
	if len(indexes) > 0 {
		indexBuf.WriteString("-- Generated by pscale import d1 convert-schema (indexes)\n")
		fmt.Fprintf(&indexBuf, "-- Source: %s\n\n", inputPath)
		indexBuf.WriteString("-- Indexes\n")
		for _, idx := range indexes {
			if IsORMMetadataTable(idx.Table) {
				continue
			}
			indexBuf.WriteString(convertIndexDDL(idx.RawDDL))
			indexBuf.WriteString("\n")
		}
		indexBuf.WriteString("\n")
	}

	return SchemaParts{
		Tables:  tableBuf.String(),
		Indexes: indexBuf.String(),
	}, converted, nil
}

// ConvertSchema converts SQLite CREATE TABLE statements to PostgreSQL DDL.
func ConvertSchema(inputPath, outputPath string) (int, error) {
	parts, converted, err := ConvertSchemaParts(inputPath)
	if err != nil {
		return 0, err
	}

	var b strings.Builder
	b.WriteString(parts.Tables)
	if parts.Indexes != "" {
		b.WriteString(parts.Indexes)
	}

	if err := os.WriteFile(outputPath, []byte(b.String()), 0o600); err != nil {
		return 0, fmt.Errorf("write schema: %w", err)
	}

	return converted, nil
}

func convertTableDDL(table TableSchema, all []TableSchema, ctx *TypeCoercionContext) string {
	var b strings.Builder
	fmt.Fprintf(&b, "CREATE TABLE IF NOT EXISTS %s (\n", postgres.QuoteIdentifier(table.Name))

	var lines []string
	for _, col := range table.Columns {
		lines = append(lines, "  "+convertColumn(col, table, all, ctx))
	}
	for _, constraint := range table.Constraints {
		if converted := convertTableConstraint(constraint); converted != "" {
			lines = append(lines, "  "+converted)
		}
	}
	b.WriteString(strings.Join(lines, ",\n"))
	b.WriteString("\n);\n")

	return b.String()
}

func convertColumn(col ColumnSchema, table TableSchema, all []TableSchema, ctx *TypeCoercionContext) string {
	pgType := sqliteTypeToPostgres(col, table, all, ctx)

	var parts []string
	parts = append(parts, postgres.QuoteIdentifier(col.Name), pgType)

	if col.AutoIncrement {
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
		if col.PrimaryKey {
			parts = append(parts, "PRIMARY KEY")
		}
	} else if col.PrimaryKey {
		parts = append(parts, "PRIMARY KEY")
	}

	if col.NotNull && !col.AutoIncrement {
		parts = append(parts, "NOT NULL")
	}

	if col.Unique {
		parts = append(parts, "UNIQUE")
	}

	if col.DefaultValue != "" && !col.AutoIncrement {
		parts = append(parts, "DEFAULT", convertDefault(col.DefaultValue, pgType))
	}

	if col.ForeignKey != "" {
		parts = append(parts, convertReferencesClause(col.ForeignKey))
	}

	return strings.Join(parts, " ")
}

func sqliteTypeToPostgres(col ColumnSchema, table TableSchema, all []TableSchema, ctx *TypeCoercionContext) string {
	if isUUIDColumn(col, table, all, ctx) {
		return "UUID"
	}

	t := strings.ToUpper(col.Type)

	if col.AutoIncrement {
		if strings.Contains(t, "BIG") {
			return "BIGINT"
		}
		return "INTEGER"
	}

	switch {
	case t == "" || t == "NUMERIC":
		return "TEXT"
	case strings.Contains(t, "INT"):
		if isBooleanLikeColumn(col, table, ctx) {
			return "BOOLEAN"
		}
		return "BIGINT"
	case strings.Contains(t, "CHAR") || strings.Contains(t, "CLOB") || strings.Contains(t, "TEXT"):
		if isJSONText(col) && ctx != nil && samplesAllowJSON(table.Name, col.Name, ctx) {
			return "JSONB"
		}
		if isTimestampText(col) && ctx != nil && samplesAllowTimestamp(table.Name, col.Name, ctx) {
			return "TIMESTAMPTZ"
		}
		return "TEXT"
	case strings.Contains(t, "BLOB"):
		return "BYTEA"
	case strings.Contains(t, "REAL") || strings.Contains(t, "FLOA") || strings.Contains(t, "DOUB"):
		return "DOUBLE PRECISION"
	case strings.Contains(t, "BOOL"):
		return "BOOLEAN"
	default:
		return "TEXT"
	}
}

func convertDefault(def, pgType string) string {
	def = strings.TrimSpace(def)
	upper := strings.ToUpper(def)
	if upper == "NULL" {
		return "NULL"
	}
	if mapped := mapSQLiteDefaultFunction(def, pgType); mapped != "" {
		return mapped
	}
	if pgType == "BOOLEAN" && (def == "0" || def == "1") {
		if def == "1" {
			return "TRUE"
		}
		return "FALSE"
	}
	if pgType == "UUID" {
		def = strings.Trim(def, "'\"")
		return "'" + def + "'"
	}
	if strings.HasPrefix(def, "'") || strings.HasPrefix(def, `"`) {
		return def
	}
	if pgType == "TEXT" || pgType == "TIMESTAMPTZ" {
		return "'" + strings.Trim(def, "'\"") + "'"
	}
	return def
}

func mapSQLiteDefaultFunction(def, pgType string) string {
	trimmed := strings.TrimSpace(def)
	upper := strings.ToUpper(trimmed)
	switch upper {
	case "CURRENT_TIMESTAMP", "(CURRENT_TIMESTAMP)":
		return "CURRENT_TIMESTAMP"
	case "CURRENT_DATE", "(CURRENT_DATE)":
		return "CURRENT_DATE"
	case "CURRENT_TIME", "(CURRENT_TIME)":
		return "CURRENT_TIME"
	}
	if strings.HasPrefix(upper, "DATETIME(") || strings.HasPrefix(upper, "(DATETIME(") {
		return "now()"
	}
	if arg := sqliteFunctionArg(trimmed, "UNIXEPOCH"); arg != "" || strings.HasSuffix(upper, "UNIXEPOCH()") {
		if mapped := mapUnixEpochDefault(arg, pgType); mapped != "" {
			return mapped
		}
	}
	return ""
}

func mapUnixEpochDefault(arg, pgType string) string {
	modifier := strings.ToUpper(strings.Trim(strings.TrimSpace(arg), `'"`))
	switch modifier {
	case "", "NOW":
		return unixEpochNowDefault(pgType)
	case "SUBSEC":
		return unixEpochSubsecDefault(pgType)
	}
	if pgType == "TIMESTAMPTZ" && unixEpochArgLooksNumeric(arg) {
		return "to_timestamp(" + strings.TrimSpace(arg) + ")"
	}
	if (pgType == "BIGINT" || pgType == "INTEGER" || pgType == "DOUBLE PRECISION") && unixEpochArgLooksNumeric(arg) {
		return strings.TrimSpace(arg)
	}
	return ""
}

func unixEpochNowDefault(pgType string) string {
	switch pgType {
	case "TIMESTAMPTZ":
		return "now()"
	case "BIGINT", "INTEGER":
		return "extract(epoch from now())::bigint"
	case "DOUBLE PRECISION":
		return "extract(epoch from now())"
	default:
		return "now()"
	}
}

func unixEpochSubsecDefault(pgType string) string {
	switch pgType {
	case "TIMESTAMPTZ":
		return "clock_timestamp()"
	case "BIGINT", "INTEGER":
		return "extract(epoch from clock_timestamp())::bigint"
	case "DOUBLE PRECISION":
		return "extract(epoch from clock_timestamp())"
	default:
		return "clock_timestamp()"
	}
}

func unixEpochArgLooksNumeric(arg string) bool {
	arg = strings.TrimSpace(arg)
	if arg == "" {
		return false
	}
	unquoted := strings.Trim(arg, `'"`)
	if _, err := strconv.ParseFloat(unquoted, 64); err == nil {
		return true
	}
	return !strings.HasPrefix(arg, "'") && !strings.HasPrefix(arg, `"`)
}

func sqliteFunctionArg(s, fn string) string {
	fnUpper := strings.ToUpper(fn)
	idx := strings.Index(strings.ToUpper(s), fnUpper+"(")
	if idx < 0 {
		return ""
	}
	start := idx + len(fnUpper) + 1
	depth := 1
	for i := start; i < len(s); i++ {
		switch s[i] {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 {
				return strings.TrimSpace(s[start:i])
			}
		}
	}
	return ""
}

// ConvertCreateStatement converts a raw SQLite CREATE TABLE line to Postgres (for tests).
func ConvertCreateStatement(sqliteDDL string) string {
	ddl := sqliteTypeCleanup.ReplaceAllString(sqliteDDL, "")
	ddl = regexp.MustCompile(`(?i)\bAUTOINCREMENT\b`).ReplaceAllString(ddl, "")
	ddl = regexp.MustCompile(`(?i)\bINTEGER\b`).ReplaceAllStringFunc(ddl, func(s string) string {
		return "BIGINT"
	})
	ddl = regexp.MustCompile(`(?i)\bREAL\b`).ReplaceAllString(ddl, "DOUBLE PRECISION")
	return ddl
}
