package d1

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"

	"github.com/planetscale/cli/internal/postgres"
)

var (
	sqliteTypeCleanup = regexp.MustCompile(`(?i)\s+PRIMARY\s+KEY\s+AUTOINCREMENT`)
)

// SchemaParts holds table DDL and secondary index DDL separately so imports can
// load data before building indexes (much faster than maintaining indexes per row).
type SchemaParts struct {
	Tables  string
	Indexes string
}

// ConvertSchemaParts converts SQLite DDL into Postgres table and index SQL.
func ConvertSchemaParts(inputPath string) (SchemaParts, int, error) {
	tables, err := ParseDump(inputPath)
	if err != nil {
		return SchemaParts{}, 0, err
	}

	coerceCtx, err := BuildTypeCoercionContext(inputPath, tables)
	if err != nil {
		return SchemaParts{}, 0, err
	}

	indexes, err := ParseIndexes(inputPath)
	if err != nil {
		return SchemaParts{}, 0, err
	}

	var tableBuf strings.Builder
	tableBuf.WriteString("-- Generated by pscale import d1 convert-schema (tables)\n")
	fmt.Fprintf(&tableBuf, "-- Source: %s\n\n", inputPath)

	converted := 0
	tableByName := make(map[string]TableSchema, len(tables))
	for _, table := range tables {
		tableByName[table.Name] = table
	}
	for _, name := range topologicalLoadOrder(tables) {
		table, ok := tableByName[name]
		if !ok {
			continue
		}
		if IsORMMetadataTable(table.Name) {
			continue
		}
		tableBuf.WriteString(convertTableDDL(table, tables, coerceCtx))
		tableBuf.WriteString("\n\n")
		converted++
	}

	var indexBuf strings.Builder
	if len(indexes) > 0 {
		indexBuf.WriteString("-- Generated by pscale import d1 convert-schema (indexes)\n")
		fmt.Fprintf(&indexBuf, "-- Source: %s\n\n", inputPath)
		indexBuf.WriteString("-- Indexes\n")
		for _, idx := range indexes {
			if IsORMMetadataTable(idx.Table) {
				continue
			}
			ddl := convertIndexDDL(idx.RawDDL)
			if ddl == "" {
				continue
			}
			indexBuf.WriteString(ddl)
			indexBuf.WriteString("\n")
		}
		indexBuf.WriteString("\n")
	}

	return SchemaParts{
		Tables:  tableBuf.String(),
		Indexes: indexBuf.String(),
	}, converted, nil
}

// ConvertSchema converts SQLite CREATE TABLE statements to PostgreSQL DDL.
func ConvertSchema(inputPath, outputPath string) (int, error) {
	parts, converted, err := ConvertSchemaParts(inputPath)
	if err != nil {
		return 0, err
	}

	var b strings.Builder
	b.WriteString(parts.Tables)
	if parts.Indexes != "" {
		b.WriteString(parts.Indexes)
	}

	if err := os.WriteFile(outputPath, []byte(b.String()), 0o600); err != nil {
		return 0, fmt.Errorf("write schema: %w", err)
	}

	return converted, nil
}

type tableConvertOptions struct {
	omitForeignKeys bool
}

func convertTableDDL(table TableSchema, all []TableSchema, ctx *TypeCoercionContext) string {
	return convertTableDDLWithOptions(table, all, ctx, tableConvertOptions{})
}

func convertTableDDLWithOptions(table TableSchema, all []TableSchema, ctx *TypeCoercionContext, opts tableConvertOptions) string {
	var b strings.Builder
	fmt.Fprintf(&b, "CREATE TABLE IF NOT EXISTS %s (\n", postgres.QuoteIdentifier(table.Name))

	var lines []string
	for _, col := range table.Columns {
		lines = append(lines, "  "+convertColumnWithOptions(col, table, all, ctx, opts))
	}
	for _, constraint := range table.Constraints {
		if converted := convertTableConstraintWithOptions(constraint, table, all, ctx, opts); converted != "" {
			lines = append(lines, "  "+converted)
		}
	}
	b.WriteString(strings.Join(lines, ",\n"))
	b.WriteString("\n);\n")

	return b.String()
}

func buildDeferredForeignKeysSQL(tables []TableSchema, ctx *TypeCoercionContext) string {
	tableByName := make(map[string]TableSchema, len(tables))
	for _, table := range tables {
		tableByName[table.Name] = table
	}

	var b strings.Builder
	for _, name := range topologicalLoadOrder(tables) {
		table, ok := tableByName[name]
		if !ok || IsORMMetadataTable(table.Name) {
			continue
		}
		for _, alter := range collectDeferredForeignKeyAlters(table, tables, ctx) {
			b.WriteString(alter)
		}
	}
	return b.String()
}

func collectDeferredForeignKeyAlters(table TableSchema, all []TableSchema, ctx *TypeCoercionContext) []string {
	var alters []string
	unnamed := 0
	for _, col := range table.Columns {
		if col.ForeignKey == "" {
			continue
		}
		refs := convertReferencesClause(col.ForeignKey, all)
		if refs == "" {
			continue
		}
		fk := "FOREIGN KEY (" + postgres.QuoteIdentifier(col.Name) + ") " + refs
		unnamed++
		name := fmt.Sprintf("d1_fk_%s_%s", table.Name, col.Name)
		alters = append(alters, formatForeignKeyAlter(table.Name, name, fk))
	}
	for _, constraint := range table.Constraints {
		clause := strings.TrimSpace(constraint)
		clause = strings.TrimSuffix(clause, ",")
		upper := strings.ToUpper(clause)
		switch {
		case strings.HasPrefix(upper, "CONSTRAINT "):
			cname, body := parseColumnNameAndRest(strings.TrimSpace(clause[len("CONSTRAINT"):]))
			if cname == "" || !strings.HasPrefix(strings.ToUpper(strings.TrimSpace(body)), "FOREIGN KEY") {
				continue
			}
			fk := convertForeignKeyConstraint(body, table, all)
			if fk == "" {
				continue
			}
			alters = append(alters, formatForeignKeyAlter(table.Name, cname, fk))
		case strings.HasPrefix(upper, "FOREIGN KEY"):
			fk := convertForeignKeyConstraint(clause, table, all)
			if fk == "" {
				continue
			}
			unnamed++
			name := fmt.Sprintf("d1_fk_%s_%d", table.Name, unnamed)
			alters = append(alters, formatForeignKeyAlter(table.Name, name, fk))
		}
	}
	return alters
}

func formatForeignKeyAlter(tableName, constraintName, fkClause string) string {
	return fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s %s;\n",
		postgres.QuoteIdentifier(tableName),
		postgres.QuoteIdentifier(constraintName),
		fkClause)
}

func convertColumn(col ColumnSchema, table TableSchema, all []TableSchema, ctx *TypeCoercionContext) string {
	return convertColumnWithOptions(col, table, all, ctx, tableConvertOptions{})
}

func convertColumnWithOptions(col ColumnSchema, table TableSchema, all []TableSchema, ctx *TypeCoercionContext, opts tableConvertOptions) string {
	pgType := sqliteTypeToPostgres(col, table, all, ctx)

	var parts []string
	parts = append(parts, postgres.QuoteIdentifier(col.Name), pgType)

	// Generated (computed) columns cannot have a DEFAULT in Postgres; the generation
	// expression takes its place. Postgres only supports STORED generated columns
	// (pre-18), so VIRTUAL columns are materialized as STORED as the closest
	// equivalent rather than silently dropping the computation.
	if col.GeneratedExpr != "" {
		parts = append(parts, "GENERATED ALWAYS AS ("+convertCheckExpr(col.GeneratedExpr, table, ctx)+") STORED")
	}

	if col.AutoIncrement {
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
		if col.PrimaryKey {
			parts = append(parts, "PRIMARY KEY")
		}
	} else if col.PrimaryKey {
		parts = append(parts, "PRIMARY KEY")
	}

	if col.NotNull && !col.AutoIncrement {
		parts = append(parts, "NOT NULL")
	}

	if col.Unique {
		parts = append(parts, "UNIQUE")
	}

	if col.DefaultValue != "" && !col.AutoIncrement && col.GeneratedExpr == "" {
		if def, ok := convertDefault(col.DefaultValue, pgType); ok {
			parts = append(parts, "DEFAULT", def)
		}
	}

	for _, check := range col.CheckExprs {
		parts = append(parts, "CHECK ("+convertCheckExpr(check, table, ctx)+")")
	}

	if col.ForeignKey != "" && !opts.omitForeignKeys {
		if refs := convertReferencesClause(col.ForeignKey, all); refs != "" {
			parts = append(parts, refs)
		}
	}

	return strings.Join(parts, " ")
}

func sqliteTypeToPostgres(col ColumnSchema, table TableSchema, all []TableSchema, ctx *TypeCoercionContext) string {
	if isUUIDColumn(col, table, all, ctx) {
		return "UUID"
	}

	t := strings.ToUpper(col.Type)

	if col.AutoIncrement {
		if strings.Contains(t, "BIG") {
			return "BIGINT"
		}
		return "INTEGER"
	}

	switch {
	case t == "":
		return "TEXT"
	case strings.Contains(t, "INT"):
		if isBooleanLikeColumn(col, table, ctx) {
			return "BOOLEAN"
		}
		return "BIGINT"
	case strings.Contains(t, "CHAR") || strings.Contains(t, "CLOB") || strings.Contains(t, "TEXT"):
		if isJSONText(col) && ctx != nil && samplesAllowJSON(table.Name, col.Name, ctx) {
			return "JSONB"
		}
		if isTimestampText(col) && ctx != nil && samplesAllowTimestamp(table.Name, col.Name, ctx) {
			return "TIMESTAMPTZ"
		}
		return "TEXT"
	case strings.Contains(t, "BLOB"):
		return "BYTEA"
	case strings.Contains(t, "REAL") || strings.Contains(t, "FLOA") || strings.Contains(t, "DOUB"):
		return "DOUBLE PRECISION"
	case strings.Contains(t, "BOOL"):
		return "BOOLEAN"
	case strings.Contains(t, "NUMERIC") || strings.Contains(t, "DECIMAL"):
		return numericPostgresType(t)
	default:
		return "TEXT"
	}
}

// numericPostgresType maps a SQLite NUMERIC/DECIMAL affinity type (already upper-cased) to
// a Postgres NUMERIC type, preserving any declared precision/scale, e.g. "DECIMAL(10,2)" ->
// "NUMERIC(10,2)".
func numericPostgresType(t string) string {
	idx := strings.Index(t, "(")
	if idx < 0 {
		return "NUMERIC"
	}
	end := strings.Index(t[idx:], ")")
	if end < 0 {
		return "NUMERIC"
	}
	return "NUMERIC" + t[idx:idx+end+1]
}

func convertDefault(def, pgType string) (string, bool) {
	def = strings.TrimSpace(def)
	upper := strings.ToUpper(def)
	if upper == "NULL" {
		return "NULL", true
	}
	quotedLiteral := strings.HasPrefix(def, "'") || strings.HasPrefix(def, `"`)
	if args, ok := bareSQLiteFunctionArgs(def, "STRFTIME"); ok {
		if mapped := mapStrftimeNowDefault(args, pgType); mapped != "" {
			return mapped, true
		}
		if pgType != "TEXT" {
			return "", false
		}
	} else if !quotedLiteral && strings.Contains(upper, "STRFTIME(") && pgType != "TEXT" {
		return "", false
	}
	if mapped := mapSQLiteDefaultFunction(def, pgType); mapped != "" {
		return mapped, true
	}
	if mapped := mapSQLiteCastDefault(def, pgType); mapped != "" {
		return mapped, true
	}
	if pgType == "BOOLEAN" {
		if lit := parseBooleanDefaultLiteral(unwrapOuterParens(def)); lit != "" {
			return lit, true
		}
		if bu := strings.ToUpper(unwrapOuterParens(def)); bu == "TRUE" || bu == "FALSE" {
			return bu, true
		}
	}
	if pgType == "UUID" {
		return convertUUIDDefault(def)
	}
	if strings.HasPrefix(def, "'") {
		if lit, ok := validatedSingleQuotedLiteral(def); ok {
			return lit, true
		}
		return "", false
	}
	if strings.HasPrefix(def, `"`) {
		inner, ok := validatedDoubleQuotedLiteral(def)
		if !ok {
			return "", false
		}
		// SQLite's double-quoted string-literal fallback: Postgres always treats double
		// quotes as identifiers, so re-quote as a proper single-quoted string literal.
		return quotePostgresLiteral(inner), true
	}
	if pgType == "TEXT" || pgType == "TIMESTAMPTZ" {
		return quotePostgresLiteral(strings.Trim(def, "'\"")), true
	}
	// Typed non-text columns (BIGINT, NUMERIC, BYTEA, …): only emit validated scalar
	// literals. Never pass an unrecognized attacker-controlled expression through
	// verbatim into executed DDL — that lets unbalanced ")" / ";" escape CREATE TABLE.
	if lit, ok := safeNumericDefaultLiteral(def); ok {
		return lit, true
	}
	return "", false
}

// convertUUIDDefault emits a safely quoted UUID default, or omits unrecognized input.
func convertUUIDDefault(def string) (string, bool) {
	def = strings.TrimSpace(def)
	if strings.HasPrefix(def, "'") {
		return validatedSingleQuotedLiteral(def)
	}
	if strings.HasPrefix(def, `"`) {
		inner, ok := validatedDoubleQuotedLiteral(def)
		if !ok {
			return "", false
		}
		return quotePostgresLiteral(inner), true
	}
	if isSafeBareUUIDDefault(def) {
		return quotePostgresLiteral(def), true
	}
	return "", false
}

// validatedSingleQuotedLiteral accepts a complete SQLite/Postgres single-quoted string
// literal (with doubled-apostrophe escapes) and rejects unclosed quotes or trailing junk after the
// closing quote — both of which can break out of DEFAULT into adjacent SQL.
func validatedSingleQuotedLiteral(s string) (string, bool) {
	s = strings.TrimSpace(s)
	if len(s) < 2 || s[0] != '\'' {
		return "", false
	}
	for i := 1; i < len(s); i++ {
		if s[i] != '\'' {
			continue
		}
		if i+1 < len(s) && s[i+1] == '\'' {
			i++
			continue
		}
		if i != len(s)-1 {
			return "", false
		}
		return s, true
	}
	return "", false
}

// validatedDoubleQuotedLiteral accepts a complete double-quoted SQLite string-literal
// fallback (with "" escapes) and returns the unescaped inner text. Trailing junk after
// the closing quote is rejected.
func validatedDoubleQuotedLiteral(s string) (string, bool) {
	s = strings.TrimSpace(s)
	if len(s) < 2 || s[0] != '"' {
		return "", false
	}
	var inner strings.Builder
	for i := 1; i < len(s); i++ {
		if s[i] != '"' {
			inner.WriteByte(s[i])
			continue
		}
		if i+1 < len(s) && s[i+1] == '"' {
			inner.WriteByte('"')
			i++
			continue
		}
		if i != len(s)-1 {
			return "", false
		}
		return inner.String(), true
	}
	return "", false
}

// isSafeBareUUIDDefault reports whether s is a bare UUID-shaped token safe to quote as a
// default (hex digits and hyphens only).
func isSafeBareUUIDDefault(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= '0' && c <= '9', c >= 'a' && c <= 'f', c >= 'A' && c <= 'F', c == '-':
		default:
			return false
		}
	}
	return true
}

// safeNumericDefaultLiteral accepts a simple numeric literal, optionally wrapped in
// balanced outer parentheses (e.g. "(0)", "((-1))"). Anything else — expressions,
// statement terminators, unbalanced parentheses — is rejected so it cannot be spliced
// into CREATE TABLE.
func safeNumericDefaultLiteral(def string) (string, bool) {
	unwrapped := strings.TrimSpace(unwrapOuterParens(def))
	if unwrapped == "" {
		return "", false
	}
	if _, err := strconv.ParseInt(unwrapped, 10, 64); err == nil {
		return unwrapped, true
	}
	if _, err := strconv.ParseFloat(unwrapped, 64); err == nil {
		upper := strings.ToUpper(unwrapped)
		if strings.Contains(upper, "INF") || strings.Contains(upper, "NAN") {
			return "", false
		}
		return unwrapped, true
	}
	lower := strings.ToLower(unwrapped)
	if strings.HasPrefix(lower, "0x") {
		hex := unwrapped[2:]
		if n, err := strconv.ParseUint(hex, 16, 64); err == nil {
			return strconv.FormatUint(n, 10), true
		}
	}
	if strings.HasPrefix(lower, "-0x") {
		hex := unwrapped[3:]
		if n, err := strconv.ParseUint(hex, 16, 63); err == nil {
			return strconv.FormatInt(-int64(n), 10), true
		}
	}
	return "", false
}

// quotePostgresLiteral wraps s as a Postgres single-quoted string literal, doubling any
// embedded single quotes so the result is always syntactically valid.
func quotePostgresLiteral(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// unwrapOuterParens repeatedly strips a single matching outer paren pair that wraps the
// entire expression, e.g. "((random()))" -> "random()".
func unwrapOuterParens(s string) string {
	for {
		s = strings.TrimSpace(s)
		if !strings.HasPrefix(s, "(") {
			return s
		}
		end, ok := matchingParenEnd(s, 0)
		if !ok || end != len(s)-1 {
			return s
		}
		s = s[1:end]
	}
}

// isBareFunctionCall reports whether s (after stripping any wrapping parens) is exactly a
// no-argument call to the named SQLite function, e.g. isBareFunctionCall("(random())", "RANDOM").
func isBareFunctionCall(s, name string) bool {
	unwrapped := strings.ToUpper(unwrapOuterParens(s))
	return unwrapped == strings.ToUpper(name)+"()"
}

// parseBooleanDefaultLiteral maps a SQLite integer DEFAULT literal to a Postgres boolean
// literal using SQLite truthiness (0 is false, any other integer is true).
func parseBooleanDefaultLiteral(def string) string {
	if n, err := strconv.ParseInt(strings.TrimSpace(def), 10, 64); err == nil {
		if n == 0 {
			return "FALSE"
		}
		return "TRUE"
	}
	return ""
}

// looksLikeUUIDGeneratorExpr detects SQLite's common "fake UUID" idiom built from
// randomblob()/hex() (e.g. lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) ||
// '-4' || lower(hex(randomblob(2))) || '-' || lower(hex(randomblob(2))) || '-' ||
// lower(hex(randomblob(6)))). The idiom concatenates several hex(randomblob(...)) segments
// with literal '-' separators to mimic the 8-4-4-4-12 UUID layout, which distinguishes it
// from a single bare `randomblob(N)` byte-string default (not a UUID at all).
func looksLikeUUIDGeneratorExpr(def string) bool {
	upper := strings.ToUpper(def)
	if strings.Count(upper, "RANDOMBLOB(") < 4 {
		return false
	}
	if !strings.Contains(upper, "HEX(") {
		return false
	}
	return strings.Contains(def, "-")
}

// randomBytesExpr returns a Postgres expression producing n pseudo-random bytes using only
// built-in functions (no pgcrypto dependency). n must be positive.
func randomBytesExpr(n int) string {
	blocks := (n + 15) / 16
	parts := make([]string, blocks)
	for i := 0; i < blocks; i++ {
		parts[i] = fmt.Sprintf("decode(md5(random()::text || clock_timestamp()::text || %d::text), 'hex')", i)
	}
	joined := strings.Join(parts, " || ")
	if blocks > 1 {
		joined = "(" + joined + ")"
	}
	return fmt.Sprintf("substring(%s from 1 for %d)", joined, n)
}

// randomblobArgN extracts the byte-count argument from a bare `randomblob(N)` call, or
// returns 0 if s isn't a randomblob call with a literal integer argument.
func randomblobArgN(s string) int {
	trimmed := strings.TrimSpace(s)
	if !strings.HasPrefix(strings.ToUpper(trimmed), "RANDOMBLOB(") {
		return 0
	}
	arg := sqliteFunctionArg(trimmed, "RANDOMBLOB")
	n, err := strconv.Atoi(strings.TrimSpace(arg))
	if err != nil {
		return 0
	}
	return n
}

func mapSQLiteDefaultFunction(def, pgType string) string {
	trimmed := strings.TrimSpace(def)
	upper := strings.ToUpper(trimmed)
	switch upper {
	case "CURRENT_TIMESTAMP", "(CURRENT_TIMESTAMP)":
		return "CURRENT_TIMESTAMP"
	case "CURRENT_DATE", "(CURRENT_DATE)":
		return "CURRENT_DATE"
	case "CURRENT_TIME", "(CURRENT_TIME)":
		return "CURRENT_TIME"
	}
	if strings.HasPrefix(upper, "DATETIME(") || strings.HasPrefix(upper, "(DATETIME(") {
		return "now()"
	}
	if strings.HasPrefix(upper, "DATE(") || strings.HasPrefix(upper, "(DATE(") {
		return "CURRENT_DATE"
	}
	if strings.HasPrefix(upper, "TIME(") || strings.HasPrefix(upper, "(TIME(") {
		if pgType == "TEXT" {
			return "to_char(now(), 'HH24:MI:SS')"
		}
		return "CURRENT_TIME"
	}
	if arg := sqliteFunctionArg(trimmed, "UNIXEPOCH"); arg != "" || strings.HasSuffix(upper, "UNIXEPOCH()") {
		if mapped := mapUnixEpochDefault(arg, pgType); mapped != "" {
			return mapped
		}
	}
	if arg, ok := bareSQLiteFunctionArgs(trimmed, "STRFTIME"); ok {
		if mapped := mapStrftimeNowDefault(arg, pgType); mapped != "" {
			return mapped
		}
	}
	if arg := sqliteFunctionArg(trimmed, "JULIANDAY"); arg != "" || strings.HasSuffix(upper, "JULIANDAY()") {
		modifier := strings.ToUpper(strings.Trim(strings.TrimSpace(arg), `'"`))
		if modifier == "" || modifier == "NOW" {
			return "(extract(epoch from now()) / 86400.0 + 2440587.5)"
		}
	}
	// Recognize the fake-UUID idiom independent of pgType/sample-based inference: a
	// schema-only dump (no sampled rows) or a column whose samples didn't happen to match
	// the UUID shape never gets pgType == "UUID" from isUUIDColumn, but the DEFAULT
	// expression's shape alone is enough to know the intent.
	if looksLikeUUIDGeneratorExpr(trimmed) {
		if pgType == "UUID" {
			return "gen_random_uuid()"
		}
		return "gen_random_uuid()::text"
	}
	if (pgType == "BIGINT" || pgType == "INTEGER") && isBareFunctionCall(trimmed, "RANDOM") {
		return "(floor(random() * 9223372036854775807))::bigint"
	}
	unwrapped := unwrapOuterParens(trimmed)
	if n := randomblobArgN(unwrapped); n > 0 {
		if pgType == "BYTEA" {
			return randomBytesExpr(n)
		}
		// Non-BYTEA columns (e.g. TEXT) can't take a bytea-typed DEFAULT; fall back to a
		// hex-encoded text representation, matching the HEX(randomblob(...)) case below.
		return "encode(" + randomBytesExpr(n) + ", 'hex')"
	}
	if n := randomblobArgN(sqliteFunctionArg(unwrapped, "HEX")); n > 0 {
		return "encode(" + randomBytesExpr(n) + ", 'hex')"
	}
	return ""
}

// mapSQLiteCastDefault recognizes `CAST(expr AS type)` DEFAULT expressions and, when the
// inner expr is a recognized SQLite function call, maps it to a Postgres equivalent
// producing the requested target type instead of silently becoming a literal string.
func mapSQLiteCastDefault(def, pgType string) string {
	trimmed := unwrapOuterParens(def)
	upper := strings.ToUpper(trimmed)
	if !strings.HasPrefix(upper, "CAST(") {
		return ""
	}
	end, ok := matchingParenEnd(trimmed, 4)
	if !ok {
		return ""
	}
	inner := trimmed[5:end]
	asIdx := indexOutsideQuotes(strings.ToUpper(inner), " AS ")
	if asIdx < 0 {
		return ""
	}
	innerExpr := strings.TrimSpace(inner[:asIdx])
	castType := strings.ToUpper(strings.TrimSpace(inner[asIdx+len(" AS "):]))

	var innerPgType string
	wantText := false
	switch {
	case strings.Contains(castType, "INT"):
		innerPgType = "BIGINT"
	case strings.Contains(castType, "REAL") || strings.Contains(castType, "FLOA") || strings.Contains(castType, "DOUB"):
		innerPgType = "DOUBLE PRECISION"
	case strings.Contains(castType, "CHAR") || strings.Contains(castType, "TEXT") || strings.Contains(castType, "CLOB"):
		innerPgType = "BIGINT"
		wantText = true
	default:
		return ""
	}

	mapped := mapSQLiteDefaultFunction(innerExpr, innerPgType)
	if mapped == "" {
		return ""
	}
	if wantText {
		return "(" + mapped + ")::text"
	}
	return mapped
}

func mapUnixEpochDefault(arg, pgType string) string {
	modifier := strings.ToUpper(strings.Trim(strings.TrimSpace(arg), `'"`))
	switch modifier {
	case "", "NOW":
		return unixEpochNowDefault(pgType)
	case "SUBSEC":
		return unixEpochSubsecDefault(pgType)
	}
	if pgType == "TIMESTAMPTZ" && unixEpochArgLooksNumeric(arg) {
		return "to_timestamp(" + strings.TrimSpace(arg) + ")"
	}
	if (pgType == "BIGINT" || pgType == "INTEGER" || pgType == "DOUBLE PRECISION") && unixEpochArgLooksNumeric(arg) {
		return strings.TrimSpace(arg)
	}
	return ""
}

func unixEpochNowDefault(pgType string) string {
	switch pgType {
	case "TIMESTAMPTZ":
		return "now()"
	case "BIGINT", "INTEGER":
		return "extract(epoch from now())::bigint"
	case "DOUBLE PRECISION":
		return "extract(epoch from now())"
	default:
		return "now()"
	}
}

func unixEpochSubsecDefault(pgType string) string {
	switch pgType {
	case "TIMESTAMPTZ":
		return "clock_timestamp()"
	case "BIGINT", "INTEGER":
		return "extract(epoch from clock_timestamp())::bigint"
	case "DOUBLE PRECISION":
		return "extract(epoch from clock_timestamp())"
	default:
		return "clock_timestamp()"
	}
}

func unixEpochArgLooksNumeric(arg string) bool {
	arg = strings.TrimSpace(arg)
	if arg == "" {
		return false
	}
	unquoted := strings.Trim(arg, `'"`)
	if _, err := strconv.ParseFloat(unquoted, 64); err == nil {
		return true
	}
	return !strings.HasPrefix(arg, "'") && !strings.HasPrefix(arg, `"`)
}

var strftimeIntervalModifierRe = regexp.MustCompile(`(?i)^([+-]?\d+(?:\.\d+)?)\s+(days?|hours?|minutes?|seconds?)$`)

var strftimeStartOfModifierRe = regexp.MustCompile(`(?i)^start of (day|month|year)$`)

// strftimeTimeValueExpr maps SQLite's current-time values to Postgres.
func strftimeTimeValueExpr(arg string) (string, bool) {
	trimmed := strings.TrimSpace(arg)
	if strings.HasPrefix(trimmed, "'") || strings.HasPrefix(trimmed, `"`) {
		if strings.ToUpper(strings.Trim(trimmed, `'"`)) == "NOW" {
			return "now()", true
		}
		return "", false
	}
	switch strings.ToUpper(trimmed) {
	case "CURRENT_TIMESTAMP":
		return "now()", true
	case "CURRENT_TIME":
		return "(TIMESTAMPTZ '2000-01-01 00:00:00+00' + ((now() AT TIME ZONE 'UTC') - date_trunc('day', now() AT TIME ZONE 'UTC')))", true
	case "CURRENT_DATE":
		return utcDateTrunc("day", "now()"), true
	}
	return "", false
}

func applyStrftimeModifiers(base string, modifiers []string) (expr string, ok bool) {
	expr = base
	for _, raw := range modifiers {
		mod := strings.Trim(strings.TrimSpace(raw), `'"`)
		if strings.EqualFold(mod, "utc") || strings.EqualFold(mod, "localtime") {
			continue
		}
		if m := strftimeStartOfModifierRe.FindStringSubmatch(mod); m != nil {
			expr = utcDateTrunc(strings.ToLower(m[1]), expr)
			continue
		}
		m := strftimeIntervalModifierRe.FindStringSubmatch(mod)
		if m == nil {
			return "", false
		}
		qty, unit := m[1], strings.ToLower(m[2])
		sign := "+"
		if strings.HasPrefix(qty, "-") {
			sign, qty = "-", qty[1:]
		} else {
			qty = strings.TrimPrefix(qty, "+")
		}
		seconds := map[string]int{"second": 1, "seconds": 1, "minute": 60, "minutes": 60, "hour": 3600, "hours": 3600, "day": 86400, "days": 86400}[unit]
		duration := "make_interval(secs => (" + qty + ")::double precision * " + strconv.Itoa(seconds) + ")"
		expr = "(" + expr + " " + sign + " " + duration + ")"
	}
	return expr, true
}

func mapStrftimeNowDefault(argList, pgType string) string {
	args := splitTopLevelArgs(argList)
	if len(args) < 2 {
		return ""
	}
	timeExpr, ok := strftimeTimeValueExpr(args[1])
	if !ok {
		return ""
	}
	timeExpr, ok = applyStrftimeModifiers(timeExpr, args[2:])
	if !ok {
		return ""
	}
	format := strings.Trim(strings.TrimSpace(args[0]), `'"`)

	switch pgType {
	case "TIMESTAMPTZ":
		return mapStrftimeTimestampFormat(format, timeExpr)
	case "BIGINT", "INTEGER", "DOUBLE PRECISION":
		if format != "%s" {
			return ""
		}
		epoch := "floor(extract(epoch from " + timeExpr + "))"
		switch pgType {
		case "BIGINT":
			return epoch + "::bigint"
		case "INTEGER":
			return epoch + "::integer"
		default:
			return epoch + "::double precision"
		}
	default:
		return ""
	}
}

func mapStrftimeTimestampFormat(format, expr string) string {
	switch format {
	case "%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%d %H:%M:%S", "%FT%TZ", "%FT%T", "%F %T":
		return "date_trunc('second', " + expr + ")"
	case "%Y-%m-%dT%H:%M:%fZ", "%Y-%m-%dT%H:%M:%f", "%Y-%m-%d %H:%M:%f", "%FT%H:%M:%fZ":
		return "date_trunc('milliseconds', " + expr + ")"
	case "%Y-%m-%d", "%F":
		return utcDateTrunc("day", expr)
	default:
		return ""
	}
}

func utcDateTrunc(unit, expr string) string {
	return "date_trunc('" + unit + "', " + expr + " AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'"
}

// splitTopLevelArgs splits commas outside quoted strings.
func splitTopLevelArgs(s string) []string {
	var args []string
	inQuote := byte(0)
	start := 0
	for i := 0; i < len(s); i++ {
		switch {
		case inQuote != 0:
			if s[i] == inQuote {
				inQuote = 0
			}
		case s[i] == '\'' || s[i] == '"':
			inQuote = s[i]
		case s[i] == ',':
			args = append(args, s[start:i])
			start = i + 1
		}
	}
	args = append(args, s[start:])
	return args
}

func bareSQLiteFunctionArgs(s, name string) (string, bool) {
	s = unwrapOuterParens(s)
	open := len(name)
	if len(s) <= open || !strings.EqualFold(s[:open], name) || s[open] != '(' {
		return "", false
	}
	end, ok := matchingParenEnd(s, open)
	if !ok || end != len(s)-1 {
		return "", false
	}
	return strings.TrimSpace(s[open+1 : end]), true
}

func sqliteFunctionArg(s, fn string) string {
	fnUpper := strings.ToUpper(fn)
	idx := strings.Index(strings.ToUpper(s), fnUpper+"(")
	if idx < 0 {
		return ""
	}
	start := idx + len(fnUpper) + 1
	depth := 1
	for i := start; i < len(s); i++ {
		switch s[i] {
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 {
				return strings.TrimSpace(s[start:i])
			}
		}
	}
	return ""
}

// ConvertCreateStatement converts a raw SQLite CREATE TABLE line to Postgres (for tests).
func ConvertCreateStatement(sqliteDDL string) string {
	ddl := sqliteTypeCleanup.ReplaceAllString(sqliteDDL, "")
	ddl = regexp.MustCompile(`(?i)\bAUTOINCREMENT\b`).ReplaceAllString(ddl, "")
	ddl = regexp.MustCompile(`(?i)\bINTEGER\b`).ReplaceAllStringFunc(ddl, func(s string) string {
		return "BIGINT"
	})
	ddl = regexp.MustCompile(`(?i)\bREAL\b`).ReplaceAllString(ddl, "DOUBLE PRECISION")
	return ddl
}
