package d1

import (
	"path/filepath"
	"strings"
)

// Lint analyzes a SQLite dump for migration issues.
func Lint(inputPath string) (*LintResult, error) {
	tables, err := ParseDump(inputPath)
	if err != nil {
		return nil, err
	}

	result := &LintResult{
		InputPath:  inputPath,
		TableCount: len(tables),
		Issues:     []Issue{},
		Tables:     make([]string, 0, len(tables)),
	}

	for _, table := range tables {
		result.Tables = append(result.Tables, table.Name)
		result.Issues = append(result.Issues, lintTable(table, tables)...)
	}

	for _, issue := range result.Issues {
		switch issue.Severity {
		case SeverityError:
			result.ErrorCount++
		case SeverityWarning:
			result.WarningCount++
		}
	}

	return result, nil
}

func lintTable(table TableSchema, all []TableSchema) []Issue {
	var issues []Issue

	issues = append(issues, lintORMMetadata(table)...)
	issues = append(issues, lintIdentifiers(table)...)

	for _, col := range table.Columns {
		if col.AutoIncrement {
			issues = append(issues, Issue{
				Code:        "AUTOINCREMENT",
				Severity:    SeverityWarning,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "Will map to GENERATED BY DEFAULT AS IDENTITY",
			})
		}

		if isBooleanColumn(col) {
			issues = append(issues, Issue{
				Code:        "BOOLEAN_AS_INTEGER",
				Severity:    SeverityWarning,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "0/1 integer values will cast to boolean on import",
			})
		}

		if isTimestampText(col) {
			issues = append(issues, Issue{
				Code:        "TEXT_TIMESTAMP",
				Severity:    SeverityWarning,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "TEXT timestamps will cast to timestamptz using pgloader rules",
			})
		}

		if isJSONText(col) {
			issues = append(issues, Issue{
				Code:        "JSON_IN_TEXT",
				Severity:    SeverityInfo,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "TEXT JSON payloads can map to jsonb where detected",
			})
		}

		if isUUIDColumn(col, table, all) {
			issues = append(issues, Issue{
				Code:        "TEXT_UUID",
				Severity:    SeverityInfo,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "TEXT/UUID-style keys will map to UUID in Postgres",
			})
		}
	}

	return issues
}

func isBooleanColumn(col ColumnSchema) bool {
	name := strings.ToLower(col.Name)
	if strings.Contains(name, "is_") || strings.HasSuffix(name, "_flag") ||
		name == "active" || name == "enabled" || name == "published" {
		return col.Type == "INTEGER" || col.Type == "INT"
	}
	return false
}

func isTimestampText(col ColumnSchema) bool {
	name := strings.ToLower(col.Name)
	if strings.Contains(name, "_at") || strings.Contains(name, "timestamp") || strings.Contains(name, "date") {
		return col.Type == "TEXT"
	}
	return false
}

func isJSONText(col ColumnSchema) bool {
	name := strings.ToLower(col.Name)
	return (strings.Contains(name, "json") || strings.Contains(name, "metadata") || strings.Contains(name, "payload")) &&
		col.Type == "TEXT"
}

// LintNextSteps returns agent next steps based on lint results.
func LintNextSteps(result *LintResult) []NextStep {
	steps := []NextStep{
		{
			Command: "pscale import d1 start <database> --input " + filepath.Base(result.InputPath) + " --dry-run",
			Reason:  "Preview import plan and get a migration ID",
		},
	}
	if result.ErrorCount == 0 {
		steps = append(steps, NextStep{
			Command: "pscale import d1 start <database> --input " + filepath.Base(result.InputPath),
			Reason:  "Run import after lint passes",
		})
	}
	return steps
}
