package d1

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func testFixture(t *testing.T) string {
	t.Helper()
	return filepath.Join("testdata", "sample_d1_export.sql")
}

func requireSQLite3(t *testing.T) {
	t.Helper()
	if _, err := FindSQLite3(); err != nil {
		t.Skip("sqlite3 not installed")
	}
}

func TestParseDump(t *testing.T) {
	tables, err := ParseDump(testFixture(t))
	if err != nil {
		t.Fatalf("ParseDump: %v", err)
	}
	if len(tables) != 6 {
		t.Fatalf("expected 6 tables, got %d", len(tables))
	}
	if tables[0].Name != "users" {
		t.Fatalf("expected users table first, got %s", tables[0].Name)
	}

	var teamMembers *TableSchema
	for i := range tables {
		if tables[i].Name == "entity_links" {
			teamMembers = &tables[i]
			break
		}
	}
	if teamMembers == nil {
		t.Fatal("expected entity_links table")
	}
	if len(teamMembers.Constraints) < 2 {
		t.Fatalf("expected composite PK and FK constraints, got %v", teamMembers.Constraints)
	}
}

func TestParseIndexes(t *testing.T) {
	indexes, err := ParseIndexes(testFixture(t))
	if err != nil {
		t.Fatalf("ParseIndexes: %v", err)
	}
	if len(indexes) != 2 {
		t.Fatalf("expected 2 indexes, got %d", len(indexes))
	}
	if indexes[0].Name != "idx_users_email" {
		t.Fatalf("unexpected first index: %s", indexes[0].Name)
	}
}

func TestLint(t *testing.T) {
	result, err := Lint(testFixture(t))
	if err != nil {
		t.Fatalf("Lint: %v", err)
	}
	if result.TableCount != 6 {
		t.Fatalf("expected 6 tables, got %d", result.TableCount)
	}
	if result.ErrorCount != 0 {
		t.Fatalf("expected no errors, got %d", result.ErrorCount)
	}
	if result.WarningCount == 0 {
		t.Fatal("expected warnings for autoincrement/boolean columns")
	}

	foundAutoincrement := false
	foundDrizzle := false
	for _, issue := range result.Issues {
		if issue.Code == "AUTOINCREMENT" {
			foundAutoincrement = true
		}
		if issue.Code == "DRIZZLE_MIGRATIONS" {
			foundDrizzle = true
		}
	}
	if !foundAutoincrement {
		t.Fatal("expected AUTOINCREMENT issue")
	}
	if !foundDrizzle {
		t.Fatal("expected DRIZZLE_MIGRATIONS issue")
	}
}

func TestPlan(t *testing.T) {
	plan, err := Plan(PlanOptions{
		InputPath: testFixture(t),
		Org:       "acme",
		Database:  "mydb",
		Branch:    "main",
	})
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if plan.MigrationID == "" {
		t.Fatal("expected migration id")
	}
	if len(plan.LoadOrder) != 6 {
		t.Fatalf("expected load order length 6, got %d", len(plan.LoadOrder))
	}
	if plan.RecommendedMethod == "" {
		t.Fatal("expected recommended method")
	}
}

func TestConvertSchema(t *testing.T) {
	out := t.TempDir() + "/schema.sql"
	count, err := ConvertSchema(testFixture(t), out)
	if err != nil {
		t.Fatalf("ConvertSchema: %v", err)
	}
	if count != 4 {
		t.Fatalf("expected 4 tables converted, got %d", count)
	}
	data, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)
	checks := []string{
		"GENERATED BY DEFAULT AS IDENTITY",
		"BOOLEAN",
		"TIMESTAMPTZ",
		`FOREIGN KEY ("user_id") REFERENCES "users" ("id")`,
		`PRIMARY KEY ("entity_id", "post_id")`,
		`"id" UUID PRIMARY KEY`,
		`"entity_id" UUID NOT NULL`,
		`CREATE INDEX IF NOT EXISTS "idx_users_email"`,
		`CREATE UNIQUE INDEX IF NOT EXISTS "idx_entity_links_post"`,
		`UNIQUE`,
		`"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`,
	}
	for _, check := range checks {
		if !strings.Contains(content, check) {
			t.Fatalf("expected schema to contain %q\n%s", check, content)
		}
	}
	if strings.Contains(content, "__drizzle_migrations") || strings.Contains(content, "_prisma_migrations") {
		t.Fatal("ORM metadata tables should be skipped in schema output")
	}
}

func TestCountInsertRows(t *testing.T) {
	counts, err := CountInsertRows(testFixture(t))
	if err != nil {
		t.Fatalf("CountInsertRows: %v", err)
	}
	if counts["users"] != 2 {
		t.Fatalf("expected 2 user rows, got %d", counts["users"])
	}
	if counts["posts"] != 2 {
		t.Fatalf("expected 2 post rows, got %d", counts["posts"])
	}
}

func TestStateStore(t *testing.T) {
	t.Setenv("PSCALE_TEST_MODE", "1")

	store, err := NewStateStore()
	if err != nil {
		t.Fatal(err)
	}

	state := &MigrationState{
		MigrationID: "test123",
		Org:         "acme",
		Database:    "mydb",
		Branch:      "main",
		InputPath:   testFixture(t),
		Phase:       PhasePlanned,
	}
	if err := store.Save(state); err != nil {
		t.Fatal(err)
	}

	loaded, err := store.Load("acme", "mydb", "main", "test123")
	if err != nil {
		t.Fatal(err)
	}
	if loaded.MigrationID != "test123" {
		t.Fatalf("expected test123, got %s", loaded.MigrationID)
	}

	if err := store.Delete("acme", "mydb", "main", "test123"); err != nil {
		t.Fatal(err)
	}
}

func TestConvertTableConstraint(t *testing.T) {
	got := convertTableConstraint("FOREIGN KEY (team_id, user_id) REFERENCES teams(id)")
	want := `FOREIGN KEY ("team_id", "user_id") REFERENCES "teams" ("id")`
	if got != want {
		t.Fatalf("got %q want %q", got, want)
	}
}

func TestQuoteColumnList(t *testing.T) {
	got := quoteColumnList("org_id, slug")
	want := `"org_id", "slug"`
	if got != want {
		t.Fatalf("got %q want %q", got, want)
	}
}
