package d1

import (
	"fmt"
	"path/filepath"
	"slices"
	"strings"
)

// Lint analyzes a SQLite dump for migration issues.
func Lint(inputPath string) (*LintResult, error) {
	tables, err := ParseDump(inputPath)
	if err != nil {
		return nil, err
	}

	coerceCtx, err := BuildTypeCoercionContext(inputPath, tables)
	if err != nil {
		return nil, err
	}

	result := &LintResult{
		InputPath:  inputPath,
		TableCount: len(tables),
		Issues:     []Issue{},
		Tables:     make([]string, 0, len(tables)),
	}

	for _, table := range tables {
		result.Tables = append(result.Tables, table.Name)
		result.Issues = append(result.Issues, lintTable(table, tables, coerceCtx)...)
	}

	ddlIssues, err := lintDumpDDL(inputPath)
	if err != nil {
		return nil, err
	}
	result.Issues = append(result.Issues, ddlIssues...)

	for _, issue := range result.Issues {
		switch issue.Severity {
		case SeverityError:
			result.ErrorCount++
		case SeverityWarning:
			result.WarningCount++
		}
	}

	return result, nil
}

func lintTable(table TableSchema, all []TableSchema, ctx *TypeCoercionContext) []Issue {
	var issues []Issue

	issues = append(issues, lintORMMetadata(table)...)
	issues = append(issues, lintIdentifiers(table)...)
	issues = append(issues, lintForeignKeyReferences(table, all)...)

	for _, col := range table.Columns {
		if col.AutoIncrement {
			issues = append(issues, Issue{
				Code:        "AUTOINCREMENT",
				Severity:    SeverityWarning,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "Will map to GENERATED BY DEFAULT AS IDENTITY",
			})
		}

		if isBooleanLikeColumn(col, table, ctx) {
			issues = append(issues, Issue{
				Code:        "BOOLEAN_AS_INTEGER",
				Severity:    SeverityWarning,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "0/1 integer values will cast to boolean on import",
			})
		} else if isBooleanNameHint(col) {
			issues = append(issues, Issue{
				Code:        "BOOLEAN_NAME_MISMATCH",
				Severity:    SeverityInfo,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "Column name suggests boolean but sampled values are not 0/1; will stay integer",
			})
		}

		if isTimestampText(col) {
			severity := SeverityWarning
			remediation := "TEXT timestamps will cast to timestamptz when sampled values look like timestamps"
			if ctx != nil && !samplesAllowTimestamp(table.Name, col.Name, ctx) {
				severity = SeverityInfo
				remediation = "Column name suggests timestamps but sampled values are not timestamp-like; will stay TEXT"
			}
			issues = append(issues, Issue{
				Code:        "TEXT_TIMESTAMP",
				Severity:    severity,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: remediation,
			})
		}

		if isJSONText(col) {
			severity := SeverityInfo
			remediation := "TEXT JSON payloads map to jsonb when sampled values parse as JSON"
			if ctx != nil && !samplesAllowJSON(table.Name, col.Name, ctx) {
				remediation = "Column name suggests JSON but sampled values are not JSON; will stay TEXT"
			}
			issues = append(issues, Issue{
				Code:        "JSON_IN_TEXT",
				Severity:    severity,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: remediation,
			})
		}

		if isExplicitUUIDColumn(col) {
			severity := SeverityInfo
			remediation := "TEXT/UUID-style keys map to UUID when sampled values look like UUIDs"
			if ctx != nil && !samplesAllowUUID(table.Name, col.Name, ctx) {
				remediation = "Column name suggests UUID but sampled values are not UUID-shaped; will stay TEXT"
			}
			issues = append(issues, Issue{
				Code:        "TEXT_UUID",
				Severity:    severity,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: remediation,
			})
		} else if isUUIDColumn(col, table, all, ctx) {
			issues = append(issues, Issue{
				Code:        "TEXT_UUID",
				Severity:    SeverityInfo,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "Foreign key references a UUID column; will map to UUID in Postgres",
			})
		}
	}

	return issues
}

func lintForeignKeyReferences(table TableSchema, all []TableSchema) []Issue {
	var issues []Issue
	seen := make(map[string]struct{})

	addIssue := func(column, ref string) {
		if ref == "" || tableByName(all, ref) != nil {
			return
		}
		key := table.Name + "." + column + "->" + ref
		if _, ok := seen[key]; ok {
			return
		}
		seen[key] = struct{}{}
		issues = append(issues, Issue{
			Code:        "UNRESOLVED_FOREIGN_KEY",
			Severity:    SeverityError,
			Table:       table.Name,
			Column:      column,
			Message:     fmt.Sprintf("foreign key references missing table %q", ref),
			Remediation: "Include the referenced table in the D1 export or remove the foreign key before import",
		})
	}

	for _, col := range table.Columns {
		addIssue(col.Name, parseReferencedTableName(col.ForeignKey))
	}
	for _, constraint := range table.Constraints {
		for _, ref := range parseTableFKReferences(constraint) {
			addIssue("", ref)
		}
	}
	for _, ref := range parseTableFKReferences(table.RawDDL) {
		addIssue("", ref)
	}
	return issues
}

var booleanNameHints = []string{"active", "enabled", "published", "archived", "disabled"}

func isBooleanNameHint(col ColumnSchema) bool {
	name := strings.ToLower(col.Name)
	if !strings.HasPrefix(name, "is_") && !strings.HasSuffix(name, "_flag") && !slices.Contains(booleanNameHints, name) {
		return false
	}
	upper := strings.ToUpper(col.Type)
	return upper == "INTEGER" || upper == "INT"
}

func isBooleanLikeColumn(col ColumnSchema, table TableSchema, ctx *TypeCoercionContext) bool {
	upper := strings.ToUpper(col.Type)
	if upper != "INTEGER" && upper != "INT" {
		return false
	}
	if col.AutoIncrement {
		return false
	}
	// A foreign key column tracks its referenced primary key's real integer identity, even
	// if the sampled values in this dataset happen to only be 0/1 — coercing it to BOOLEAN
	// would mismatch the referenced (BIGINT) column's type.
	if refTable, _ := columnFKTarget(col, table); refTable != "" {
		return false
	}
	if ctx == nil {
		return false
	}
	return samplesLookBoolean(table.Name, col.Name, ctx)
}

func isTimestampText(col ColumnSchema) bool {
	return col.Type == "TEXT" && looksLikeTimestampColumnName(col.Name)
}

func looksLikeTimestampColumnName(name string) bool {
	name = strings.ToLower(name)
	if strings.Contains(name, "_at") || strings.Contains(name, "timestamp") {
		return true
	}
	if name == "date" || strings.HasSuffix(name, "_date") || strings.HasPrefix(name, "date_") {
		return true
	}
	return false
}

func isJSONText(col ColumnSchema) bool {
	name := strings.ToLower(col.Name)
	return (strings.Contains(name, "json") || strings.Contains(name, "metadata") || strings.Contains(name, "payload")) &&
		col.Type == "TEXT"
}

// LintNextSteps returns agent next steps based on lint results.
func LintNextSteps(result *LintResult) []NextStep {
	input := filepath.Base(result.InputPath)
	if result.ErrorCount > 0 {
		return []NextStep{{
			Command: "pscale import d1 lint --input " + input,
			Reason:  "Re-run lint after fixing the reported errors; import (including --dry-run) is blocked until lint passes",
		}}
	}
	return []NextStep{
		{
			Command: "pscale import d1 start <database> --input " + input + " --dry-run",
			Reason:  "Preview import plan and get a migration ID",
		},
		{
			Command: "pscale import d1 start <database> --input " + input,
			Reason:  "Run import after lint passes",
		},
	}
}
