package d1

import (
	"path/filepath"
	"strings"
)

// Lint analyzes a SQLite dump for migration issues.
func Lint(inputPath string) (*LintResult, error) {
	tables, err := ParseDump(inputPath)
	if err != nil {
		return nil, err
	}

	coerceCtx, err := BuildTypeCoercionContext(inputPath, tables)
	if err != nil {
		return nil, err
	}

	result := &LintResult{
		InputPath:  inputPath,
		TableCount: len(tables),
		Issues:     []Issue{},
		Tables:     make([]string, 0, len(tables)),
	}

	for _, table := range tables {
		result.Tables = append(result.Tables, table.Name)
		result.Issues = append(result.Issues, lintTable(table, tables, coerceCtx)...)
	}

	for _, issue := range result.Issues {
		switch issue.Severity {
		case SeverityError:
			result.ErrorCount++
		case SeverityWarning:
			result.WarningCount++
		}
	}

	return result, nil
}

func lintTable(table TableSchema, all []TableSchema, ctx *TypeCoercionContext) []Issue {
	var issues []Issue

	issues = append(issues, lintORMMetadata(table)...)
	issues = append(issues, lintIdentifiers(table)...)

	for _, col := range table.Columns {
		if col.AutoIncrement {
			issues = append(issues, Issue{
				Code:        "AUTOINCREMENT",
				Severity:    SeverityWarning,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "Will map to GENERATED BY DEFAULT AS IDENTITY",
			})
		}

		if isBooleanLikeColumn(col, table, ctx) {
			issues = append(issues, Issue{
				Code:        "BOOLEAN_AS_INTEGER",
				Severity:    SeverityWarning,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "0/1 integer values will cast to boolean on import",
			})
		} else if isBooleanNameHint(col) {
			issues = append(issues, Issue{
				Code:        "BOOLEAN_NAME_MISMATCH",
				Severity:    SeverityInfo,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "Column name suggests boolean but sampled values are not 0/1; will stay integer",
			})
		}

		if isTimestampText(col) {
			severity := SeverityWarning
			remediation := "TEXT timestamps will cast to timestamptz when sampled values look like timestamps"
			if ctx != nil && !samplesAllowTimestamp(table.Name, col.Name, ctx) {
				severity = SeverityInfo
				remediation = "Column name suggests timestamps but sampled values are not timestamp-like; will stay TEXT"
			}
			issues = append(issues, Issue{
				Code:        "TEXT_TIMESTAMP",
				Severity:    severity,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: remediation,
			})
		}

		if isJSONText(col) {
			severity := SeverityInfo
			remediation := "TEXT JSON payloads map to jsonb when sampled values parse as JSON"
			if ctx != nil && !samplesAllowJSON(table.Name, col.Name, ctx) {
				remediation = "Column name suggests JSON but sampled values are not JSON; will stay TEXT"
			}
			issues = append(issues, Issue{
				Code:        "JSON_IN_TEXT",
				Severity:    severity,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: remediation,
			})
		}

		if isExplicitUUIDColumn(col) {
			severity := SeverityInfo
			remediation := "TEXT/UUID-style keys map to UUID when sampled values look like UUIDs"
			if ctx != nil && !samplesAllowUUID(table.Name, col.Name, ctx) {
				remediation = "Column name suggests UUID but sampled values are not UUID-shaped; will stay TEXT"
			}
			issues = append(issues, Issue{
				Code:        "TEXT_UUID",
				Severity:    severity,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: remediation,
			})
		} else if isUUIDColumn(col, table, all, ctx) {
			issues = append(issues, Issue{
				Code:        "TEXT_UUID",
				Severity:    SeverityInfo,
				Table:       table.Name,
				Column:      col.Name,
				Remediation: "Foreign key references a UUID column; will map to UUID in Postgres",
			})
		}
	}

	return issues
}

func isBooleanNameHint(col ColumnSchema) bool {
	name := strings.ToLower(col.Name)
	if !strings.HasPrefix(name, "is_") && !strings.HasSuffix(name, "_flag") &&
		name != "active" && name != "enabled" && name != "published" &&
		name != "archived" && name != "disabled" {
		return false
	}
	upper := strings.ToUpper(col.Type)
	return upper == "INTEGER" || upper == "INT"
}

func isBooleanColumn(col ColumnSchema) bool {
	return isBooleanNameHint(col)
}

func isBooleanLikeColumn(col ColumnSchema, table TableSchema, ctx *TypeCoercionContext) bool {
	upper := strings.ToUpper(col.Type)
	if upper != "INTEGER" && upper != "INT" {
		return false
	}
	if ctx == nil {
		return false
	}
	return samplesLookBoolean(table.Name, col.Name, ctx)
}

func isTimestampText(col ColumnSchema) bool {
	return col.Type == "TEXT" && looksLikeTimestampColumnName(col.Name)
}

func looksLikeTimestampColumnName(name string) bool {
	name = strings.ToLower(name)
	if strings.Contains(name, "_at") || strings.Contains(name, "timestamp") {
		return true
	}
	if name == "date" || strings.HasSuffix(name, "_date") || strings.HasPrefix(name, "date_") {
		return true
	}
	return false
}

func isJSONText(col ColumnSchema) bool {
	name := strings.ToLower(col.Name)
	return (strings.Contains(name, "json") || strings.Contains(name, "metadata") || strings.Contains(name, "payload")) &&
		col.Type == "TEXT"
}

// LintNextSteps returns agent next steps based on lint results.
func LintNextSteps(result *LintResult) []NextStep {
	steps := []NextStep{
		{
			Command: "pscale import d1 start <database> --input " + filepath.Base(result.InputPath) + " --dry-run",
			Reason:  "Preview import plan and get a migration ID",
		},
	}
	if result.ErrorCount == 0 {
		steps = append(steps, NextStep{
			Command: "pscale import d1 start <database> --input " + filepath.Base(result.InputPath),
			Reason:  "Run import after lint passes",
		})
	}
	return steps
}
