sources:
  go: true
  
source_path: cmd/pscale

allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - mpl-2.0

reviewed:
  go:
    - github.com/godbus/dbus
    - github.com/sagikazarmark/slog-shim
    - github.com/tinylib/msgp/msgp
    - go.uber.org/zap/exp/**
    - github.com/magiconair/properties
    - github.com/klauspost/compress
    - github.com/dustin/go-humanize
    - github.com/DataDog/go-tuf/**/*
    - google.golang.org/protobuf/**/*
    - golang.org/x/**/*
    - github.com/xelabs/go-mysqlstack/**/*
    - github.com/klauspost/compress/**/*
