#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

export PSCALE_TEST_MODE=1

FIXTURE="$ROOT/internal/migrate/d1/testdata/sample_d1_export.sql"

echo "==> Building pscale CLI..."
go build -o ./pscale-test ./cmd/pscale

PSCALE="./pscale-test"

echo "==> import d1 doctor"
$PSCALE import d1 doctor --format json | tee /tmp/d1-doctor.json
grep -q '"status"' /tmp/d1-doctor.json

echo "==> import d1 lint"
$PSCALE import d1 lint --input "$FIXTURE" --format json | tee /tmp/d1-lint.json
grep -q '"phase": "lint"' /tmp/d1-lint.json
grep -q 'AUTOINCREMENT' /tmp/d1-lint.json

echo "==> import d1 start --dry-run (preview)"
$PSCALE import d1 start \
  --input "$FIXTURE" \
  --org testorg \
  --database testdb \
  --branch main \
  --dry-run \
  --force \
  --format json | tee /tmp/d1-preview.json
MIGRATION_ID=$(grep -o '"migration_id": "[^"]*"' /tmp/d1-preview.json | head -1 | cut -d'"' -f4)
test -n "$MIGRATION_ID"
grep -q '"dry_run": true' /tmp/d1-preview.json

echo "==> import d1 convert-schema"
SCHEMA_OUT="$(mktemp -t d1-schema.XXXXXX.sql)"
$PSCALE import d1 convert-schema --input "$FIXTURE" --output "$SCHEMA_OUT" --format json
grep -q 'GENERATED BY DEFAULT AS IDENTITY' "$SCHEMA_OUT"

echo "==> import d1 status"
$PSCALE import d1 status \
  --org testorg \
  --database testdb \
  --branch main \
  --migration-id "$MIGRATION_ID" \
  --format json | tee /tmp/d1-status.json
grep -q '"phase": "planned"' /tmp/d1-status.json

echo "==> import d1 verify (source-only, no dest URI)"
$PSCALE import d1 verify \
  --input "$FIXTURE" \
  --migration-id "$MIGRATION_ID" \
  --format json | tee /tmp/d1-verify.json || true

echo "==> import d1 start dry-run"
$PSCALE import d1 start \
  --org testorg \
  --database testdb \
  --branch main \
  --input "$FIXTURE" \
  --migration-id "$MIGRATION_ID" \
  --dry-run \
  --force \
  --format json | tee /tmp/d1-start-dryrun.json
grep -q '"dry_run": true' /tmp/d1-start-dryrun.json

echo "==> import d1 complete"
$PSCALE import d1 complete \
  --org testorg \
  --database testdb \
  --branch main \
  --migration-id "$MIGRATION_ID" \
  --force \
  --format json

echo "==> All import d1 smoke tests passed"
