agents:
  queue: "public"

steps:
- block: ":rocket: Release !"
  branches: "main"

- command: script/bump-version.sh
  if: build.branch == "main"
  label: ":arrow_up_small: Bump & tag version"

- wait

- label: ":github: Publishing artifacts"
  if: build.branch == "main"
  command: script/release.sh
