agents:
  queue: "public"

steps:
- name: "Go build and test %n"
  command: make
  plugins:
    - docker-compose#v4.14.0:
        cli-version: "2"
        run: app

- name: "Check licenses %n"
  command: make licensed
  plugins:
    - docker-compose#v4.14.0:
        cli-version: "2"
        run: licensing

- wait

- block: ":rocket: Release !"
  branches: "main"

- command: script/bump-version.sh
  if: build.branch == "main"
  label: ":arrow_up_small: Bump & tag version"

- wait

- label: ":github: Publishing artifacts"
  if: build.branch == "main"
  command: script/release.sh
