steps:
- name: "Go build and test %n"
  command: make
  plugins:
    - docker-compose#v3.7.0:
        run: app

- name: "Check licenses %n"
  command: make licensed
  plugins:
    - docker-compose#v3.7.0:
        run: licensing
