ARG GORELEASE_CROSS_VERSION=v1.20.2
FROM ghcr.io/goreleaser/goreleaser-cross:${GORELEASE_CROSS_VERSION}

ARG SYFT_VERSION=0.75.0
RUN wget -O syft.deb https://github.com/anchore/syft/releases/download/v${SYFT_VERSION}/syft_${SYFT_VERSION}_linux_amd64.deb && dpkg -i syft.deb
