#!/bin/sh

set -e

# Install Homebrew if necessary
if [[ $(uname) != "Linux" ]] ; then
    which -s brew
    if [[ $? != 0 && $(uname) != "Linux" ]] ; then
        echo "Installing Homebrew..."
        # Install Homebrew
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    else
        brew update
    fi

    echo "Installing dependencies..."
    # Install Homebrew bundle
    brew bundle
fi
